image:
  file: .gitpod.Dockerfile

tasks:
  - name: Test
    init: npm install && npm install -g eslint
    command: npm test

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==